;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2025 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 57B76064866E8CA0D5B397834F43041C19C57C49B4C0C8CF1D647036C80BE5C4
; Input MD5    : D398491E55381AC47FADC1EDB4DB757F
; Input CRC32  : E13C8465
; Compiler     : Visual C++

; File Name   : C:\Users\Anonymous\Downloads\ReverseProject\Crackme\2\WinCrackMe.exe
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 4A82B65B (Wed Aug 12 12:32:27 2009)
; Section 1. (virtual address 00001000)
; Virtual size                  : 00000C5E (   3166.)
; Section size in file          : 00000E00 (   3584.)
; Offset to raw data for section: 00000400
; Flags 60000020: Text Executable Readable
; Alignment     : default
; PDB File Name : c:\Documents and Settings\brejaud\Mes documents\Visual Studio 2008\Projects\WinCrackMe_Light\Release\WinCrackMe_Light.pdb
; OS type         :  MS Windows
; Application type:  Executable 32bit

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



; int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
_WinMain@16 proc near

Msg= tagMSG ptr -1Ch
hInstance= dword ptr  4
hPrevInstance= dword ptr  8
lpCmdLine= dword ptr  0Ch
nShowCmd= dword ptr  10h

mov     eax, [esp+hInstance]
sub     esp, 1Ch
push    esi
push    0               ; dwInitParam
push    offset DialogFunc ; lpDialogFunc
push    0               ; hWndParent
push    65h ; 'e'       ; lpTemplateName
push    eax             ; hInstance
call    ds:CreateDialogParamA
push    5               ; nCmdShow
push    eax             ; hWnd
call    ds:ShowWindow
mov     esi, ds:GetMessageA
push    0               ; wMsgFilterMax
push    0               ; wMsgFilterMin
push    0               ; hWnd
lea     ecx, [esp+2Ch+Msg]
push    ecx             ; lpMsg
call    esi ; GetMessageA
cmp     eax, 1
jnz     short loc_401072
push    ebx
mov     ebx, ds:DispatchMessageA
push    edi
mov     edi, ds:TranslateMessage
lea     esp, [esp+0]

loc_401050:
lea     edx, [esp+28h+Msg]
push    edx             ; lpMsg
call    edi ; TranslateMessage
lea     eax, [esp+28h+Msg]
push    eax             ; lpMsg
call    ebx ; DispatchMessageA
push    0               ; wMsgFilterMax
push    0               ; wMsgFilterMin
push    0               ; hWnd
lea     ecx, [esp+34h+Msg]
push    ecx             ; lpMsg
call    esi ; GetMessageA
cmp     eax, 1
jz      short loc_401050
pop     edi
pop     ebx

loc_401072:
xor     eax, eax
pop     esi
add     esp, 1Ch
retn    10h
_WinMain@16 endp

align 10h



; INT_PTR __stdcall DialogFunc(HWND, UINT, WPARAM, LPARAM)
DialogFunc proc near

hDlg= dword ptr  4
arg_4= dword ptr  8
arg_8= dword ptr  0Ch

cmp     [esp+arg_4], 111h
jnz     short loc_4010A4
movzx   eax, word ptr [esp+arg_8]
sub     eax, 9
jz      loc_4011DC
sub     eax, 3E0h
jz      short loc_4010C9
sub     eax, 1
jz      short loc_4010A9

loc_4010A4:
xor     eax, eax
retn    10h

loc_4010A9:
mov     eax, [esp+hDlg]
push    3EAh            ; nResult
push    eax             ; hDlg
call    ds:EndDialog
push    0               ; nExitCode
call    ds:PostQuitMessage
mov     eax, 1
retn    10h

loc_4010C9:
push    esi
mov     esi, [esp+4+hDlg]
push    edi
mov     edi, ds:GetDlgItemTextA
push    0FFh            ; cchMax
push    offset String   ; lpString
push    3EBh            ; nIDDlgItem
push    esi             ; hDlg
call    edi ; GetDlgItemTextA
mov     dword_403404, eax
test    eax, eax
jnz     short loc_40110C
push    eax             ; uType
push    offset Caption  ; "Error"
push    offset Text     ; "Enter your name before test !"
push    esi             ; hWnd
call    ds:MessageBoxA
pop     edi
pop     esi
mov     eax, 1
retn    10h

loc_40110C:
call    sub_401320
test    al, al
jnz     short loc_401132
push    0               ; uType
push    offset Caption  ; "Error"
push    offset aTheEnteredName ; "THE ENTERED NAME IS NOT VALID:\n Minimu"...
push    esi             ; hWnd
call    ds:MessageBoxA
pop     edi
pop     esi
mov     eax, 1
retn    10h

loc_401132:
call    sub_401380
cmp     eax, 24h ; '$'
mov     dword_403638, eax
jge     short loc_40115E
push    0               ; uType
push    offset Caption  ; "Error"
push    offset aTheEnteredName_0 ; "THE ENTERED NAME IS NOT VALID:\n This n"...
push    esi             ; hWnd
call    ds:MessageBoxA
pop     edi
pop     esi
mov     eax, 1
retn    10h

loc_40115E:             ; cchMax
push    0FFh
push    offset byte_403508 ; lpString
push    3ECh            ; nIDDlgItem
push    esi             ; hDlg
call    edi ; GetDlgItemTextA
mov     dword_403400, eax
cmp     eax, 17h
jz      short loc_401197
push    0               ; uType
push    offset Caption  ; "Error"
push    offset aTheSerialIsNot ; "THE SERIAL IS NOT VALID:\n Invalid leng"...
push    esi             ; hWnd
call    ds:MessageBoxA
pop     edi
pop     esi
mov     eax, 1
retn    10h

loc_401197:
call    sub_401200
push    0               ; uType
cmp     eax, dword_403638
jz      short loc_4011C1
push    offset Caption  ; "Error"
push    offset aTheSerialIsNot_0 ; "THE SERIAL IS NOT VALID:\n Check Name a"...
push    esi             ; hWnd
call    ds:MessageBoxA
pop     edi
pop     esi
mov     eax, 1
retn    10h

loc_4011C1:
push    offset aGoodBoy ; "Good boy !"
push    offset aSerialIsOkWrit ; "SERIAL IS OK:\n Write a KEYGEN now ..."
push    esi             ; hWnd
call    ds:MessageBoxA
pop     edi
pop     esi
mov     eax, 1
retn    10h

loc_4011DC:
mov     ecx, [esp+hDlg]
push    0               ; uType
push    offset aInstructions ; "Instructions"
push    offset aCrackMeAndWrit ; "Crack me and write a Keygen\nThat's the"...
push    ecx             ; hWnd
call    ds:MessageBoxA
mov     eax, 1
retn    10h
DialogFunc endp

align 10h



sub_401200 proc near

var_4= dword ptr -4

push    ecx
push    ebx
mov     bl, byte_403018
push    ebp
push    esi
xor     eax, eax
push    edi
xor     edi, edi
mov     [esp+14h+var_4], eax
xor     ebp, ebp
mov     esi, 4
lea     ebx, [ebx+0]

loc_401220:
mov     dl, byte_403508[esi]
xor     ecx, ecx
cmp     bl, dl
jz      short loc_40123E
lea     esp, [esp+0]

loc_401230:
cmp     ecx, 24h ; '$'
jge     short loc_40123E
inc     ecx
cmp     byte_403018[ecx], dl
jnz     short loc_401230

loc_40123E:
sub     esi, 1
mov     edx, [esp+14h+var_4]
lea     edx, [edx+edx*8]
lea     ecx, [ecx+edx*4]
mov     [esp+14h+var_4], ecx
jns     short loc_401220
mov     bl, byte_40303C
mov     esi, 0Ah
lea     esp, [esp+0]

loc_401260:
mov     dl, byte_403508[esi]
xor     ecx, ecx
cmp     bl, dl
jz      short loc_40127E
lea     esp, [esp+0]

loc_401270:
cmp     ecx, 24h ; '$'
jge     short loc_40127E
inc     ecx
cmp     byte_40303C[ecx], dl
jnz     short loc_401270

loc_40127E:
dec     esi
cmp     esi, 6
lea     edx, [edi+edi*8]
lea     edi, [ecx+edx*4]
jge     short loc_401260
mov     bl, byte_403060
mov     esi, 10h

loc_401295:
mov     dl, byte_403508[esi]
xor     ecx, ecx
cmp     bl, dl
jz      short loc_4012AF

loc_4012A1:
cmp     ecx, 24h ; '$'
jge     short loc_4012AF
inc     ecx
cmp     byte_403060[ecx], dl
jnz     short loc_4012A1

loc_4012AF:
dec     esi
cmp     esi, 0Ch
lea     edx, [ebp+ebp*8+0]
lea     ebp, [ecx+edx*4]
jge     short loc_401295
mov     bl, byte_403084
mov     esi, 16h
jmp     short loc_4012D0
align 10h

loc_4012D0:
mov     dl, byte_403508[esi]
xor     ecx, ecx
cmp     bl, dl
jz      short loc_4012EE
lea     esp, [esp+0]

loc_4012E0:
cmp     ecx, 24h ; '$'
jge     short loc_4012EE
inc     ecx
cmp     byte_403084[ecx], dl
jnz     short loc_4012E0

loc_4012EE:
dec     esi
cmp     esi, 12h
lea     eax, [eax+eax*8]
lea     eax, [ecx+eax*4]
jge     short loc_4012D0
mov     ecx, [esp+14h+var_4]
cmp     ecx, edi
jnz     short loc_401312
cmp     ecx, ebp
jnz     short loc_401312
cmp     ecx, eax
jnz     short loc_401312
pop     edi
pop     esi
pop     ebp
mov     eax, ecx
pop     ebx
pop     ecx
retn

loc_401312:
pop     edi
pop     esi
pop     ebp
xor     eax, eax
pop     ebx
pop     ecx
retn
sub_401200 endp

align 10h



sub_401320 proc near
push    ebx
mov     ebx, dword_403404
push    esi
push    edi
xor     edi, edi
xor     esi, esi
test    ebx, ebx
jle     short loc_401378
push    ebp

loc_401332:
mov     dl, String[esi]
movsx   ecx, dl
lea     eax, [ecx-41h]
mov     ebp, 19h
cmp     ebp, eax
sbb     eax, eax
add     ecx, 0FFFFFF9Fh
inc     eax
cmp     ebp, ecx
sbb     ecx, ecx
inc     ecx
lea     eax, [eax+ecx*2]
sub     eax, 1
jz      short loc_401360
sub     eax, 1
jnz     short loc_401367
sub     dl, 20h ; ' '

loc_401360:
mov     byte_403520[edi], dl
inc     edi

loc_401367:
inc     esi
cmp     esi, ebx
jl      short loc_401332
cmp     edi, 5
pop     ebp
jl      short loc_401378
pop     edi
pop     esi
mov     al, 1
pop     ebx
retn

loc_401378:
pop     edi
pop     esi
xor     al, al
pop     ebx
retn
sub_401320 endp

align 10h



sub_401380 proc near
movsx   eax, byte_403520
cmp     eax, 41h ; 'A'
jl      short loc_401391
cmp     eax, 5Ah ; 'Z'
jle     short loc_401393

loc_401391:
xor     eax, eax

loc_401393:
lea     ecx, [eax-41h]
movsx   eax, byte_403521
imul    ecx, 1Ah
cmp     eax, 41h ; 'A'
jl      short loc_4013AA
cmp     eax, 5Ah ; 'Z'
jle     short loc_4013AC

loc_4013AA:
xor     eax, eax

loc_4013AC:
lea     ecx, [eax+ecx-41h]
movsx   eax, byte_403522
imul    ecx, 1Ah
cmp     eax, 41h ; 'A'
jl      short loc_4013C4
cmp     eax, 5Ah ; 'Z'
jle     short loc_4013C6

loc_4013C4:
xor     eax, eax

loc_4013C6:
lea     ecx, [eax+ecx-41h]
movsx   eax, byte_403523
imul    ecx, 1Ah
cmp     eax, 41h ; 'A'
jl      short loc_4013DE
cmp     eax, 5Ah ; 'Z'
jle     short loc_4013E0

loc_4013DE:
xor     eax, eax

loc_4013E0:
lea     eax, [eax+ecx-41h]
movsx   ecx, byte_403524
imul    eax, 1Ah
cmp     ecx, 41h ; 'A'
jl      short loc_4013F8
cmp     ecx, 5Ah ; 'Z'
jle     short loc_4013FA

loc_4013F8:
xor     ecx, ecx

loc_4013FA:
lea     eax, [eax+ecx-41h]
retn
sub_401380 endp

; [0000000F BYTES: COLLAPSED FUNCTION __security_check_cookie(x). PRESS CTRL-NUMPAD+ TO EXPAND]
; [0000004B BYTES: COLLAPSED FUNCTION _pre_cpp_init. PRESS CTRL-NUMPAD+ TO EXPAND]
; [000001DF BYTES: COLLAPSED FUNCTION ___tmainCRTStartup. PRESS CTRL-NUMPAD+ TO EXPAND]
; [000000E1 BYTES: COLLAPSED FUNCTION _pre_c_init. PRESS CTRL-NUMPAD+ TO EXPAND]
; [0000000A BYTES: COLLAPSED FUNCTION start. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000106 BYTES: COLLAPSED FUNCTION ___report_gsfailure. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000042 BYTES: COLLAPSED FUNCTION __CxxUnhandledExceptionFilter(_EXCEPTION_POINTERS *). PRESS CTRL-NUMPAD+ TO EXPAND]



sub_40186B proc near
push    offset ?__CxxUnhandledExceptionFilter@@YGJPAU_EXCEPTION_POINTERS@@@Z ; lpTopLevelExceptionFilter
call    ds:SetUnhandledExceptionFilter
xor     eax, eax
retn
sub_40186B endp

align 2
; [00000006 BYTES: COLLAPSED FUNCTION _amsg_exit. PRESS CTRL-NUMPAD+ TO EXPAND]
; [000000A5 BYTES: COLLAPSED FUNCTION __onexit. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000017 BYTES: COLLAPSED FUNCTION _atexit. PRESS CTRL-NUMPAD+ TO EXPAND]



sub_40193C proc near
mov     edi, edi
push    esi
mov     eax, offset unk_4023A8
mov     esi, offset unk_4023A8
push    edi
mov     edi, eax
cmp     eax, esi
jnb     short loc_40195F

loc_401950:
mov     eax, [edi]
test    eax, eax
jz      short loc_401958
call    eax

loc_401958:
add     edi, 4
cmp     edi, esi
jb      short loc_401950

loc_40195F:
pop     edi
pop     esi
retn
sub_40193C endp




; void __cdecl sub_401962()
sub_401962 proc near
mov     edi, edi
push    esi
mov     eax, offset unk_4023B0
mov     esi, offset unk_4023B0
push    edi
mov     edi, eax
cmp     eax, esi
jnb     short loc_401985

loc_401976:
mov     eax, [edi]
test    eax, eax
jz      short loc_40197E
call    eax

loc_40197E:
add     edi, 4
cmp     edi, esi
jb      short loc_401976

loc_401985:
pop     edi
pop     esi
retn
sub_401962 endp

; [00000006 BYTES: COLLAPSED FUNCTION _XcptFilter. PRESS CTRL-NUMPAD+ TO EXPAND]
align 10h
; [00000035 BYTES: COLLAPSED FUNCTION __ValidateImageBase. PRESS CTRL-NUMPAD+ TO EXPAND]
align 10h
; [00000044 BYTES: COLLAPSED FUNCTION __FindPESection. PRESS CTRL-NUMPAD+ TO EXPAND]
align 10h
; [000000BD BYTES: COLLAPSED FUNCTION __IsNonwritableInCurrentImage. PRESS CTRL-NUMPAD+ TO EXPAND]
align 2
; [00000006 BYTES: COLLAPSED FUNCTION _initterm. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _initterm_e. PRESS CTRL-NUMPAD+ TO EXPAND]
align 4
; [00000045 BYTES: COLLAPSED FUNCTION __SEH_prolog4. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000014 BYTES: COLLAPSED FUNCTION __SEH_epilog4. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000025 BYTES: COLLAPSED FUNCTION __except_handler4. PRESS CTRL-NUMPAD+ TO EXPAND]
; [0000002B BYTES: COLLAPSED FUNCTION __setdefaultprecision. PRESS CTRL-NUMPAD+ TO EXPAND]



; int __cdecl UserMathErrorFunction(struct _exception *)
UserMathErrorFunction proc near
xor     eax, eax
retn
UserMathErrorFunction endp

; [00000096 BYTES: COLLAPSED FUNCTION ___security_init_cookie. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _crt_debugger_hook. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION terminate(void). PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _unlock. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION __dllonexit. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _lock. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _except_handler4_common. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _invoke_watson. PRESS CTRL-NUMPAD+ TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _controlfp_s. PRESS CTRL-NUMPAD+ TO EXPAND]
align 200h
dd 80h dup(?)
_text ends

; Section 2. (virtual address 00002000)
; Virtual size                  : 000008C8 (   2248.)
; Section size in file          : 00000A00 (   2560.)
; Offset to raw data for section: 00001200
; Flags 40000040: Data Readable
; Alignment     : default
;
; Imports from KERNEL32.dll
;

; Segment type: Externs
; _idata
; void (__stdcall *GetSystemTimeAsFileTime)(LPFILETIME lpSystemTimeAsFileTime)
extrn GetSystemTimeAsFileTime:dword
; DWORD (__stdcall *GetCurrentProcessId)()
extrn GetCurrentProcessId:dword
; DWORD (__stdcall *GetCurrentThreadId)()
extrn GetCurrentThreadId:dword
; DWORD (__stdcall *GetTickCount)()
extrn GetTickCount:dword
; BOOL (__stdcall *QueryPerformanceCounter)(LARGE_INTEGER *lpPerformanceCount)
extrn QueryPerformanceCounter:dword
; BOOL (__stdcall *IsDebuggerPresent)()
extrn IsDebuggerPresent:dword
; LPTOP_LEVEL_EXCEPTION_FILTER (__stdcall *SetUnhandledExceptionFilter)(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter)
extrn SetUnhandledExceptionFilter:dword
; LONG (__stdcall *UnhandledExceptionFilter)(struct _EXCEPTION_POINTERS *ExceptionInfo)
extrn UnhandledExceptionFilter:dword
; HANDLE (__stdcall *GetCurrentProcess)()
extrn GetCurrentProcess:dword
; void (__stdcall *GetStartupInfoA)(LPSTARTUPINFOA lpStartupInfo)
extrn GetStartupInfoA:dword
; LONG (__stdcall *InterlockedCompareExchange)(volatile LONG *Destination, LONG Exchange, LONG Comperand)
extrn InterlockedCompareExchange:dword
; void (__stdcall *Sleep)(DWORD dwMilliseconds)
extrn Sleep:dword
; LONG (__stdcall *InterlockedExchange)(volatile LONG *Target, LONG Value)
extrn InterlockedExchange:dword
; BOOL (__stdcall *TerminateProcess)(HANDLE hProcess, UINT uExitCode)
extrn TerminateProcess:dword

;
; Imports from MSVCR90.dll
;
; int (__cdecl *ismbblead)(unsigned int Ch)
extrn _ismbblead:dword
; void (__cdecl __noreturn *exit)(int Code)
extrn exit:dword
; char *acmdln
extrn _acmdln:dword
; void (__cdecl *_initterm)(_PVFV *First, _PVFV *Last)
extrn __imp__initterm:dword
; int (__cdecl *_initterm_e)(_PIFV *First, _PIFV *Last)
extrn __imp__initterm_e:dword
; int (__cdecl *configthreadlocale)(int Flag)
extrn _configthreadlocale:dword
extrn __imp__XcptFilter:dword
extrn _adjust_fdiv:dword
; int *(__cdecl *_p__commode)()
extrn __p__commode:dword
; int *(__cdecl *_p__fmode)()
extrn __p__fmode:dword
extrn _encode_pointer:dword
; void (__cdecl *_set_app_type)(_crt_app_type Type)
extrn __set_app_type:dword
extrn __imp__crt_debugger_hook:dword
; __declspec(dllimport) void __cdecl terminate(void)
extrn __imp_?terminate@@YAXXZ:dword
extrn __imp__unlock:dword
extrn __imp___dllonexit:dword
extrn __imp__lock:dword
; _onexit_t (__cdecl *onexit)(_onexit_t Func)
extrn _onexit:dword
extrn _decode_pointer:dword
extrn __imp__except_handler4_common:dword
; void (__cdecl __noreturn *_invoke_watson)(const wchar_t *Expression, const wchar_t *FunctionName, const wchar_t *FileName, unsigned int LineNo, uintptr_t Reserved)
extrn __imp__invoke_watson:dword
; errno_t (__cdecl *_controlfp_s)(unsigned int *CurrentState, unsigned int NewValue, unsigned int Mask)
extrn __imp__controlfp_s:dword
; void (__cdecl __noreturn *exit)(int Code)
extrn _exit:dword
; void (__cdecl *cexit)()
extrn _cexit:dword
extrn __getmainargs:dword
extrn __imp__amsg_exit:dword
; void (__cdecl *_setusermatherr)(_UserMathErrorFunctionPointer UserMathErrorFunction)
extrn __setusermatherr:dword

;
; Imports from USER32.dll
;
; BOOL (__stdcall *GetMessageA)(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax)
extrn GetMessageA:dword
; HWND (__stdcall *CreateDialogParamA)(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam)
extrn CreateDialogParamA:dword
; void (__stdcall *PostQuitMessage)(int nExitCode)
extrn PostQuitMessage:dword
; BOOL (__stdcall *TranslateMessage)(const MSG *lpMsg)
extrn TranslateMessage:dword
; int (__stdcall *MessageBoxA)(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType)
extrn MessageBoxA:dword
; BOOL (__stdcall *EndDialog)(HWND hDlg, INT_PTR nResult)
extrn EndDialog:dword
; BOOL (__stdcall *ShowWindow)(HWND hWnd, int nCmdShow)
extrn ShowWindow:dword
; LRESULT (__stdcall *DispatchMessageA)(const MSG *lpMsg)
extrn DispatchMessageA:dword
; UINT (__stdcall *GetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPSTR lpString, int cchMax)
extrn GetDlgItemTextA:dword



; Segment type: Pure data
; Segment permissions: Read
_rdata segment para public 'DATA' use32
assume cs:_rdata
;org 4020D4h
; const _PVFV dword_4020D4
dword_4020D4 dd 0
dd offset _pre_cpp_init
; const _PVFV dword_4020DC
dword_4020DC dd 0
; const _PIFV First
First dd 0
dd offset _pre_c_init
dd offset sub_40186B
; const _PIFV Last
Last dd 0
; Debug Directory entries
dd 0                    ; Characteristics
dd 4A82B65Bh            ; TimeDateStamp: Wed Aug 12 12:32:27 2009
dw 0                    ; MajorVersion
dw 0                    ; MinorVersion
dd 2                    ; Type: IMAGE_DEBUG_TYPE_CODEVIEW
dd 92h                  ; SizeOfData
dd rva asc_402300       ; AddressOfRawData
dd 1500h                ; PointerToRawData
; const struct _EXCEPTION_POINTERS ExceptionInfo
ExceptionInfo _EXCEPTION_POINTERS <offset dword_4030C8,\
                     offset dword_403120>
; const CHAR Caption[]
Caption db 'Error',0
align 4
; const CHAR Text[]
Text db 'Enter your name before test !',0
align 10h
; const CHAR aTheEnteredName[]
aTheEnteredName db 'THE ENTERED NAME IS NOT VALID:',0Ah
db ' Minimum of valid characters is not'
db ' reached...',0
align 10h
; const CHAR aTheEnteredName_0[]
aTheEnteredName_0 db 'THE ENTERED NAME IS NOT VALID:',0Ah
db ' This name is a joke...',0
align 4
; const CHAR aTheSerialIsNot[]
aTheSerialIsNot db 'THE SERIAL IS NOT VALID:',0Ah
db ' Invalid lenght...',0
; const CHAR aTheSerialIsNot_0[]
aTheSerialIsNot_0 db 'THE SERIAL IS NOT VALID:',0Ah
db ' Check Name and Serial ...',0
; const CHAR aGoodBoy[]
aGoodBoy db 'Good boy !',0
align 4
; const CHAR aSerialIsOkWrit[]
aSerialIsOkWrit db 'SERIAL IS OK:',0Ah
db ' Write a KEYGEN now ...',0
align 4
; const CHAR aInstructions[]
aInstructions db 'Instructions',0
align 10h
; const CHAR aCrackMeAndWrit[]
aCrackMeAndWrit db 'Crack me and write a Keygen',0Ah
db 'That',27h,'s the stuff ..',0Ah
db '(c) KIDMUNCHER 2009',0
align 8
__load_config_used dd 48h ; Size
dd 0                    ; Time stamp
dw 2 dup(0)             ; Version: 0.0
dd 0                    ; GlobalFlagsClear
dd 0                    ; GlobalFlagsSet
dd 0                    ; CriticalSectionDefaultTimeout
dd 0                    ; DeCommitFreeBlockThreshold
dd 0                    ; DeCommitTotalFreeThreshold
dd 0                    ; LockPrefixTable
dd 0                    ; MaximumAllocationSize
dd 0                    ; VirtualMemoryThreshold
dd 0                    ; ProcessHeapFlags
dd 0                    ; ProcessAffinityMask
dw 0                    ; CSDVersion
dw 0                    ; Reserved1
dd 0                    ; EditList
dd offset ___security_cookie ; SecurityCookie
dd offset ___safe_se_handler_table ; SEHandlerTable
dd 1                    ; SEHandlerCount
; Debug information (IMAGE_DEBUG_TYPE_CODEVIEW)
asc_402300 db 'RSDS'    ; CV signature
GUID <0B77EEAD6h, 0B224h, 4591h, <0AEh, \ ; GUID
      1Bh, 15h, 64h, 68h, 0E8h, 54h, \
      0D9h>>
dd 2                    ; Age
text "UTF-8", 'c:\Documents and Setting' ; PdbFileName
text "UTF-8", 's\brejaud\Mes documents\'
text "UTF-8", 'Visual Studio 2008\Proje'
text "UTF-8", 'cts\WinCrackMe_Light\Rel'
text "UTF-8", 'ease\WinCrackMe_Light.pd'
text "UTF-8", 'b',0
align 10h
___safe_se_handler_table dd rva __except_handler4
align 8
unk_4023A8 db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
unk_4023B0 db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
stru_4023B8 _EH4_SCOPETABLE <0FFFFFFFEh, 0, \
                 0FFFFFF88h, 0, <\
                 0FFFFFFFEh, \
                 offset loc_40161F, \
                 offset loc_401623>, <\
                 0FFFFFFFEh, \
                 offset loc_4015D3, \
                 offset loc_4015E7>>
stru_4023E0 _EH4_SCOPETABLE <0FFFFFFFEh, 0, \
                 0FFFFFFCCh, 0, <\
                 0FFFFFFFEh, 0, \
                 offset loc_40191C>>
align 10h
stru_402400 _EH4_SCOPETABLE <0FFFFFFFEh, 0, \
                 0FFFFFFD8h, 0, <\
                 0FFFFFFFEh, \
                 offset loc_401AAB, \
                 offset loc_401ABF>>
__IMPORT_DESCRIPTOR_USER32 dd rva off_402518 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aUser32Dll       ; DLL Name
dd rva GetMessageA      ; Import Address Table
__IMPORT_DESCRIPTOR_MSVCR90 dd rva off_4024A8 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aMsvcr90Dll      ; DLL Name
dd rva _ismbblead       ; Import Address Table
__IMPORT_DESCRIPTOR_KERNEL32 dd rva off_40246C ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aKernel32Dll     ; DLL Name
dd rva GetSystemTimeAsFileTime ; Import Address Table
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
;
; Import names for KERNEL32.dll
;
off_40246C dd rva word_4028A0
dd rva word_40288A
dd rva word_402874
dd rva word_402864
dd rva word_40284A
dd rva word_402836
dd rva word_402818
dd rva word_4027FC
dd rva word_4027E8
dd rva word_4027C2
dd rva word_4027A4
dd rva word_40279C
dd rva word_402786
dd rva word_4027D4
dd 0
;
; Import names for MSVCR90.dll
;
off_4024A8 dd rva word_402622
dd rva word_402630
dd rva word_402638
dd rva word_402642
dd rva word_40264E
dd rva word_40265C
dd rva word_402614
dd rva word_402686
dd rva word_402696
dd rva word_4026A6
dd rva word_4026B4
dd rva word_4026C6
dd rva word_4026D8
dd rva word_4026EE
dd rva word_40270E
dd rva word_402718
dd rva word_402726
dd rva word_40272E
dd rva word_402738
dd rva word_40274A
dd rva word_402764
dd rva word_402776
dd rva word_40260C
dd rva word_402602
dd rva word_4025F2
dd rva word_4025E4
dd rva word_402672
dd 0
;
; Import names for USER32.dll
;
off_402518 dd rva word_4025CA
dd rva word_4025B4
dd rva word_4025A2
dd rva word_40258E
dd rva word_402580
dd rva word_402574
dd rva word_402566
dd rva word_402552
dd rva word_402540
dd 0
word_402540 dw 121h
db 'GetDlgItemTextA',0
word_402552 dw 0A8h
db 'DispatchMessageA',0
align 2
word_402566 dw 2B8h
db 'ShowWindow',0
align 4
word_402574 dw 0D3h
db 'EndDialog',0
word_402580 dw 1F8h
db 'MessageBoxA',0
word_40258E dw 2D5h
db 'TranslateMessage',0
align 2
word_4025A2 dw 220h
db 'PostQuitMessage',0
word_4025B4 dw 5Ch
db 'CreateDialogParamA',0
align 2
word_4025CA dw 14Ah
db 'GetMessageA',0
aUser32Dll db 'USER32.dll',0
align 4
word_4025E4 dw 115h
db '_amsg_exit',0
align 2
word_4025F2 dw 9Fh
db '__getmainargs',0
word_402602 dw 12Ch
db '_cexit',0
align 4
word_40260C dw 17Ch
db '_exit',0
word_402614 dw 66h
db '_XcptFilter',0
word_402622 dw 225h
db '_ismbblead',0
align 10h
word_402630 dw 4CCh
db 'exit',0
align 4
word_402638 dw 0FDh
db '_acmdln',0
word_402642 dw 204h
db '_initterm',0
word_40264E dw 205h
db '_initterm_e',0
word_40265C dw 13Ch
db '_configthreadlocale',0
word_402672 dw 0E3h
db '__setusermatherr',0
align 2
word_402686 dw 10Bh
db '_adjust_fdiv',0
align 2
word_402696 dw 0CBh
db '__p__commode',0
align 2
word_4026A6 dw 0CFh
db '__p__fmode',0
align 4
word_4026B4 dw 16Ah
db '_encode_pointer',0
word_4026C6 dw 0E0h
db '__set_app_type',0
align 4
word_4026D8 dw 14Bh
db '_crt_debugger_hook',0
align 2
word_4026EE dw 43h
db '?terminate@@YAXXZ',0
aMsvcr90Dll db 'MSVCR90.dll',0
word_40270E dw 3E6h
db '_unlock',0
word_402718 dw 96h
db '__dllonexit',0
word_402726 dw 276h
db '_lock',0
word_40272E dw 31Ch
db '_onexit',0
word_402738 dw 160h
db '_decode_pointer',0
word_40274A dw 173h
db '_except_handler4_common',0
word_402764 dw 20Bh
db '_invoke_watson',0
align 2
word_402776 dw 13Fh
db '_controlfp_s',0
align 2
word_402786 dw 2BDh
db 'InterlockedExchange',0
word_40279C dw 421h
db 'Sleep',0
word_4027A4 dw 2BAh
db 'InterlockedCompareExchange',0
align 2
word_4027C2 dw 239h
db 'GetStartupInfoA',0
word_4027D4 dw 42Dh
db 'TerminateProcess',0
align 4
word_4027E8 dw 1A9h
db 'GetCurrentProcess',0
word_4027FC dw 43Eh
db 'UnhandledExceptionFilter',0
align 4
word_402818 dw 415h
db 'SetUnhandledExceptionFilter',0
word_402836 dw 2D1h
db 'IsDebuggerPresent',0
word_40284A dw 354h
db 'QueryPerformanceCounter',0
word_402864 dw 266h
db 'GetTickCount',0
align 4
word_402874 dw 1ADh
db 'GetCurrentThreadId',0
align 2
word_40288A dw 1AAh
db 'GetCurrentProcessId',0
word_4028A0 dw 24Fh
db 'GetSystemTimeAsFileTime',0
aKernel32Dll db 'KERNEL32.dll',0
align 800h
_rdata ends

; Section 3. (virtual address 00003000)
; Virtual size                  : 00000654 (   1620.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00001C00
; Flags C0000040: Data Readable Writable
; Alignment     : default

; Segment type: Pure data
; Segment permissions: Read/Write
_data segment para public 'DATA' use32
assume cs:_data
;org 403000h
; uintptr_t __security_cookie
___security_cookie dd 0BB40E64Eh
dword_403004 dd 44BF19B1h
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
dword_403010 dd 0FFFFFFFEh
dword_403014 dd 1
byte_403018 db 41h
db  47h ; G
db  4Dh ; M
db  53h ; S
db  59h ; Y
db  34h ; 4
db  42h ; B
db  48h ; H
db  4Eh ; N
db  54h ; T
db  5Ah ; Z
db  35h ; 5
db  43h ; C
db  49h ; I
db  4Fh ; O
db  55h ; U
db  30h ; 0
db  36h ; 6
db  44h ; D
db  4Ah ; J
db  50h ; P
db  56h ; V
db  31h ; 1
db  37h ; 7
db  45h ; E
db  4Bh ; K
db  51h ; Q
db  57h ; W
db  32h ; 2
db  38h ; 8
db  46h ; F
db  4Ch ; L
db  52h ; R
db  58h ; X
db  33h ; 3
db  39h ; 9
byte_40303C db 42h
db  48h ; H
db  4Eh ; N
db  54h ; T
db  5Ah ; Z
db  35h ; 5
db  43h ; C
db  49h ; I
db  4Fh ; O
db  55h ; U
db  30h ; 0
db  36h ; 6
db  44h ; D
db  4Ah ; J
db  50h ; P
db  56h ; V
db  31h ; 1
db  37h ; 7
db  45h ; E
db  4Bh ; K
db  51h ; Q
db  57h ; W
db  32h ; 2
db  38h ; 8
db  46h ; F
db  4Ch ; L
db  52h ; R
db  58h ; X
db  33h ; 3
db  39h ; 9
db  41h ; A
db  47h ; G
db  4Dh ; M
db  53h ; S
db  59h ; Y
db  34h ; 4
byte_403060 db 43h
db  49h ; I
db  4Fh ; O
db  55h ; U
db  30h ; 0
db  36h ; 6
db  44h ; D
db  4Ah ; J
db  50h ; P
db  56h ; V
db  31h ; 1
db  37h ; 7
db  45h ; E
db  4Bh ; K
db  51h ; Q
db  57h ; W
db  32h ; 2
db  38h ; 8
db  46h ; F
db  4Ch ; L
db  52h ; R
db  58h ; X
db  33h ; 3
db  39h ; 9
db  41h ; A
db  47h ; G
db  4Dh ; M
db  53h ; S
db  59h ; Y
db  34h ; 4
db  42h ; B
db  48h ; H
db  4Eh ; N
db  54h ; T
db  5Ah ; Z
db  35h ; 5
byte_403084 db 44h
aJpv17ekqw28flr db 'JPV17EKQW28FLRX39AGMSY4BHNTZ5CIOU06'
db 0
align 4
unk_4030AC db    0
db    0
db    0
db    0
unk_4030B0 db    0
db    0
db    0
db    0
dword_4030B4 dd 0
dword_4030B8 dd 0
dword_4030BC dd 0
dword_4030C0 dd 0
dword_4030C4 dd 0
dword_4030C8 dd 0
dword_4030CC dd 0
db    0
db    0
db    0
db    0
dword_4030D4 dd 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_403118 dd 0
align 10h
dword_403120 dd 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
word_4031AC dw 0
align 10h
word_4031B0 dw 0
align 4
word_4031B4 dw 0
align 4
word_4031B8 dw 0
align 4
dword_4031BC dd 0
dword_4031C0 dd 0
dword_4031C4 dd 0
dword_4031C8 dd 0
dword_4031CC dd 0
dword_4031D0 dd 0
dword_4031D4 dd 0
dword_4031D8 dd 0
word_4031DC dw 0
align 10h
dword_4031E0 dd 0
dword_4031E4 dd 0
word_4031E8 dw 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
dword_4033EC dd ?
dword_4033F0 dd ?
dword_4033F4 dd ?
dword_4033F8 dd ?
align 10h
dword_403400 dd ?
dword_403404 dd ?
; CHAR String
String db ?
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
; CHAR byte_403508
byte_403508 db ?
align 20h
byte_403520 db ?
byte_403521 db ?
byte_403522 db ?
byte_403523 db ?
byte_403524 db ?
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
db    ? ;
dword_403638 dd ?
dword_40363C dd ?
dword_403640 dd ?
; LONG Target
Target dd ?
dword_403648 dd ?
dword_40364C dd ?
dword_403650 dd ?
align 1000h
_data ends


end start
